"""Bring the VPN-tunnelled container stack up and down.

The stack: gluetun (ProtonVPN / WireGuard) + qBittorrent routed *through* it +
Prowlarr alongside. qBittorrent shares gluetun's network namespace
(`network_mode: service:protonvpn`), so its torrent traffic exits via the VPN
while the host's own network is untouched. gluetun's kill switch stops the
attached container's traffic if the tunnel drops, so there's no leak.

Secrets come from settings (never hardcoded), are written to a .env beside a
generated compose file, and the whole thing is driven with `docker compose`.
Lifecycle: `up` starts it (waiting for the tunnel), `down` tears it all down and
leaves the host back to normal.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import httpx

from .config import Config
from .ui import UI

# gluetun's control server, published on the host, reports the tunnel's public IP.
GLUETUN_CONTROL = "http://localhost:8000/v1/publicip/ip"

COMPOSE_TEMPLATE = """# Generated by torrent-cli — do not edit; edit settings instead.
services:
  protonvpn:
    image: qmcgaw/gluetun:latest
    container_name: torrentcli-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-protonvpn}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-}
      - FIREWALL_OUTBOUND_SUBNETS=${LAN_SUBNET:-172.16.0.0/12}
    volumes:
      - ./gluetun-auth.toml:/gluetun/auth/config.toml:ro
    ports:
      - "8080:8080"   # qBittorrent WebUI (shares this namespace)
      - "8000:8000"   # gluetun control server (tunnel status)
    networks: [arrnet]
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: torrentcli-qbittorrent
    network_mode: "service:protonvpn"   # <- routed through the tunnel
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config
      - ./downloads:/downloads
    depends_on:
      - protonvpn
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: torrentcli-prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - prowlarr-config:/config
    ports:
      - "9696:9696"
    networks: [arrnet]
    restart: unless-stopped

networks:
  arrnet:

volumes:
  prowlarr-config:
  qbittorrent-config:
"""

# gluetun v3.40+ requires auth on its control server; allow only the read-only
# public-IP status route (so we can poll tunnel status without a key).
GLUETUN_AUTH = """[[roles]]
name = "status"
routes = ["GET /v1/publicip/ip"]
auth = "none"
"""


class StackError(Exception):
    pass


def stack_dir() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or (Path.home() / ".config")
    return Path(base) / "torrent-cli" / "stack"


def _compose_cmd() -> list[str]:
    if shutil.which("docker") is None:
        raise StackError("docker not found on PATH — is Docker installed and running?")
    return ["docker", "compose"]


def _render(config: Config) -> Path:
    """Write the compose file and a .env (secrets from settings) to the stack dir."""
    d = stack_dir()
    (d / "downloads").mkdir(parents=True, exist_ok=True)
    (d / "docker-compose.yml").write_text(COMPOSE_TEMPLATE)
    (d / "gluetun-auth.toml").write_text(GLUETUN_AUTH)
    env = {
        "VPN_SERVICE_PROVIDER": config.vpn_provider,
        "WIREGUARD_PRIVATE_KEY": config.wireguard_private_key,
        "WIREGUARD_ADDRESSES": config.wireguard_addresses,
        "SERVER_COUNTRIES": config.vpn_server_countries,
        "PUID": str(os.getuid()),
        "PGID": str(os.getgid()),
    }
    (d / ".env").write_text("".join(f"{k}={v}\n" for k, v in env.items()))
    return d


def _run(d: Path, *args: str, capture: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        [*_compose_cmd(), *args], cwd=d, text=True,
        capture_output=capture,
    )


def tunnel_ip(timeout: float = 3.0) -> str | None:
    """The VPN exit IP if the tunnel is up, else None."""
    try:
        resp = httpx.get(GLUETUN_CONTROL, timeout=timeout)
        if resp.status_code == 200:
            return resp.json().get("public_ip") or None
    except (httpx.HTTPError, ValueError):
        pass
    return None


def up(config: Config, ui: UI) -> int:
    if not config.vpn_configured():
        ui.error("No VPN key configured. Set wireguard_private_key and "
                 "wireguard_addresses in settings (config.toml).")
        return 1
    try:
        d = _render(config)
    except StackError as exc:
        ui.error(str(exc))
        return 1

    ui.info("Bringing up the VPN stack (gluetun + qBittorrent + Prowlarr)…")
    result = _run(d, "up", "-d")
    if result.returncode != 0:
        ui.error("docker compose up failed.")
        return 1

    ui.info("Waiting for the VPN tunnel to establish…")
    ip = _wait_for_tunnel(ui)
    if ip is None:
        ui.error("VPN tunnel didn't come up in time — check your ProtonVPN "
                 "WireGuard key/address. Tearing the stack back down.")
        _run(d, "down")
        return 1

    ui.success(f"VPN up — container traffic exits via {ip}.")
    ui.info("Point Prowlarr's download client at host 'protonvpn' port 8080.")
    ui.info("Run `torrent-cli down` when you're finished to tear it all down.")
    return 0


def _wait_for_tunnel(ui: UI, attempts: int = 30) -> str | None:
    import time

    for _ in range(attempts):
        ip = tunnel_ip()
        if ip:
            return ip
        time.sleep(2)
    return None


def down(config: Config, ui: UI) -> int:
    d = stack_dir()
    if not (d / "docker-compose.yml").exists():
        ui.info("No VPN stack found to tear down.")
        return 0
    ui.info("Tearing down the VPN stack…")
    result = _run(d, "down")
    if result.returncode != 0:
        ui.error("docker compose down reported an error.")
        return 1
    ui.success("VPN stack down — host is back to normal.")
    return 0


def status(config: Config, ui: UI) -> int:
    ip = tunnel_ip()
    if ip:
        ui.success(f"VPN tunnel is up — exit IP {ip}.")
    else:
        ui.info("VPN tunnel is not up (stack not running, or still connecting).")
    return 0
